apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx-deployment
  labels:
    app: frontend-nginx
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend-nginx
      env: production
  template:
    metadata:
      labels:
        app: app-frontend-nginx
        env: production
    spec:
      containers:
        - name: app-frontend-nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-persistent-storage
              mountPath: /usr/share/nginx/html   
      volumes: 
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: nginx-pvc      

   