apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels: 
    app: frontend-nginx
    env: production
spec:
  type: LoadBalancer
  selector:
    app: app-frontend-nginx
    env: production
  ports: 
    - port: 80
      targetPort: 80

